project tt/Models/Config.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int Id { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public string Facebook { get; set; }
        public string vnp_Url { get; set; }
        public string vnp_Returnurl { get; set; }
        public string vnpay_api_url { get; set; }
        public string vnp_TmnCode { get; set; }
        public string vnp_HashSecret { get; set; }
    }
}

project tt/Areas/Admin/Controllers/ConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using ProjectFinal.Models;
using ProjectFinal.Repositories;

namespace ProjectFinal.Areas.Admin.Controllers
{
    public class ConfigController : BaseController
    {
        private readonly IConfigRepositiory _configRepositiory;
        ProjectFinalEntities db = new ProjectFinalEntities();

        public ConfigController(IConfigRepositiory configRepositiory)
        {
            _configRepositiory = configRepositiory;
        }


        public ActionResult Edit()
        {
            var model = db.Config.SingleOrDefault();
            var viewModel = Mapper.Map<Config, ConfigModel>(model);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(ConfigModel model)
        {
            if (ModelState.IsValid)
            {
                _configRepositiory.Update(model);
                return RedirectToAction("Index","Home");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

project tt/Areas/Admin/Views/Config/Edit.cshtml
@model ProjectFinal.Models.ConfigModel
@{
    ViewBag.Title = "Sửa cấu hình";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Sửa danh mục
        </h1>
        <ol class="breadcrumb">
            <li><a href="Admin/Home/Index"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            <li class="active">Sửa cấu hình hệ thống</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        @using (Html.BeginForm("Edit", "Config", FormMethod.Post, new { Area = "Admin", enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(model=> model.Id)
                            @Html.ValidationSummary(false, "", new { @class = "error" })
                            <div class="form-group">
                                <label>Số điện thoại</label>
                                @Html.TextBoxFor(model => model.Phone, new { @class = "form-control", @id = "txtName" })
                                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                <label>Facebook</label>
                                @Html.TextBoxFor(model => model.Facebook, new { @class = "form-control", @id = "txtName" })
                                @Html.ValidationMessageFor(model => model.Facebook, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                <label>Email</label>
                                @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label>vnp_TmnCode</label>
                                @Html.TextBoxFor(model => model.vnp_TmnCode, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.vnp_TmnCode, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                <label>vnp_Returnurl</label>
                                @Html.TextBoxFor(model => model.vnp_Returnurl, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.vnp_Returnurl, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                <label>vnp_Returnurl</label>
                                @Html.TextBoxFor(model => model.vnp_Url, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.vnp_Url, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                <label>vnp_TmnCode</label>
                                @Html.TextBoxFor(model => model.vnp_HashSecret, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.vnp_HashSecret, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-5">
                                    <input type="submit" value="Cập nhật" class="btn btn-success" />
                                </div>
                            </div>
                        }
                        <div>
                            <a class="btn btn-danger" href="@Url.Action("Index", "Home", new { Area = "Admin" })">Quay lại</a>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>