project tt/Models/Service.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Money { get; set; }
        public string Descripttion { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> Status { get; set; }
    }
}

project tt/Areas/Admin/Controllers/ServiceController.cs
using AutoMapper;
using ProjectFinal.Common;
using ProjectFinal.Models;
using ProjectFinal.Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectFinal.Areas.Admin.Controllers
{
    public class ServiceController : BaseController
    {
        // GET: Admin/Service
        private readonly IServices _service;

        public ServiceController(IServices service)
        {
            _service = service;
        }

        public ActionResult Index()
        {
            ViewBag.ListService = _service.GetListService();
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ServiceModel serviceModel)
        {
            if (ModelState.IsValid)
            {
                if (serviceModel.LogoFile == null || serviceModel.LogoFile.ContentLength == 0)
                {
                    serviceModel.Image = null;
                }
                else
                {
                    string fileName = Path.GetFileNameWithoutExtension(serviceModel.LogoFile.FileName);
                    string extention = Path.GetExtension(serviceModel.LogoFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extention;
                    serviceModel.Image = "/UploadFiles/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/UploadFiles/"), fileName);
                    serviceModel.LogoFile.SaveAs(fileName);
                }
                _service.Add(serviceModel);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            var model=_service.GetServiceDetail(id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            var viewModel= Mapper.Map<Service, ServiceModel>(model);           
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(ServiceModel serviceModel)
        {
            var service = _service.GetServiceDetail(serviceModel.Id);
            if (ModelState.IsValid)
            {
                if (serviceModel.LogoFile == null || serviceModel.LogoFile.ContentLength == 0)
                {
                    serviceModel.Image = service.Image;
                }
                else
                {
                    string fileName = Path.GetFileNameWithoutExtension(serviceModel.LogoFile.FileName);
                    string extention = Path.GetExtension(serviceModel.LogoFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extention;
                    serviceModel.Image = "/UploadFiles/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/UploadFiles/"), fileName);
                    serviceModel.LogoFile.SaveAs(fileName);
                }
                _service.Update(serviceModel);
                return RedirectToAction("Index");
            }
            else
            {
                var model = _service.GetServiceDetail(serviceModel.Id);
                var viewModel = Mapper.Map<Service, ServiceModel>(model);
                viewModel.Money = Convert.ToDecimal(CommonUtil.RenderPrice(viewModel.Money));
                return View(viewModel);
            }
        }

        public ActionResult Delete(int id)
        {
            var model = _service.GetServiceDetail(id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            _service.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

project tt/Areas/Admin/Views/Service/Create.cshtml
@model ProjectFinal.Models.ServiceModel
@{
    ViewBag.Title = "Thêm chiến dịch";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section footerJS{
    <script src="~/Assets/admin/libs/ckeditor/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#desc'), {
                // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
               // minHeight: '300px'
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(err => {
                console.error(err.stack);
            });
    </script>
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Thêm mới chiến dịch
        </h1>
        <ol class="breadcrumb">
            <li><a href="Admin/Home/Index"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            <li><a href="Admin/Service/Index">Chiến dịch</a></li>
            <li class="active">Thêm chiến dịch</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        @using (Html.BeginForm("Create", "Service", FormMethod.Post, new { Area = "Admin", enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tên chiến dịch</label>
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @id = "txtName" })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Số tiền</label>
                                @Html.TextBoxFor(model => model.Money, new { type = "number", @class = "form-control decimalnumber" })
                                @Html.ValidationMessageFor(model => model.Money, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Mô tả</label>
                                @Html.TextAreaFor(model => model.Descripttion, new { @class = "form-control",@id="desc" })
                                @Html.ValidationMessageFor(model => model.Descripttion, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Từ ngày</label>
                                @Html.TextBoxFor(model => model.FromDate, "{0:yyyy-MM-ddTHH:mm:ss}", new { @class = "form-control", @type = "datetime-local" })
                                @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Đến ngày ngày</label>
                                @Html.TextBoxFor(model => model.ToDate, "{0:yyyy-MM-ddTHH:mm:ss}", new { @class = "form-control", @type = "datetime-local" })
                                @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Logo</label>
                                <input type="file" name="LogoFile" class="form-control" />
                                @Html.ValidationMessageFor(model => model.LogoFile, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Trạng thái</label>
                                <select class="form-control" id="Status" name="Status">
                                    <option value="1" selected>Hoạt động</option>
                                    <option value="0">Khóa</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-5">
                                    <input type="submit" value="Thêm mới" class="btn btn-success" />
                                </div>
                            </div>
                        }
                        <div>
                            <a class="btn btn-danger" href="@Url.Action("Index", "Service", new { Area = "Admin" })">Quay lại</a>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

project tt/Areas/Admin/Views/Service/Edit.cshtml
@model ProjectFinal.Models.ServiceModel
@{
    ViewBag.Title = "Sửa chiến dịch";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section footerJS{

    <script src="~/Assets/admin/libs/ckeditor/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#desc'), {
                // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
               // minHeight: '300px'
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(err => {
                console.error(err.stack);
            });

    </script>
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Sửa chiến dịch
        </h1>
        <ol class="breadcrumb">
            <li><a href="Admin/Home/Index"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            <li><a href="Admin/Service/Index">Chiến dịch</a></li>
            <li class="active">Sửa chiến dịch</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        @using (Html.BeginForm("Edit", "Service", FormMethod.Post, new { Area = "Admin", enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(false, "", new { @class = "error" })
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tên chiến dịch</label>
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @id = "txtName" })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Số tiền</label>
                                @Html.TextBoxFor(model => model.Money, "{0:###0}", new { type = "number", @class = "form-control decimalnumber" })
                                @Html.ValidationMessageFor(model => model.Money, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Mô tả</label>
                                @Html.TextAreaFor(model => model.Descripttion, new { @class = "form-control", @id = "desc" })
                                @Html.ValidationMessageFor(model => model.Descripttion, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Ngày bắt đầu</label>
                                @Html.TextBoxFor(model => model.FromDate, "{0:yyyy-MM-ddTHH:mm:ss}", new { @class = "form-control", @type = "datetime-local", @value = "model => model.FromDate" })
                                @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Ngày kết thúc</label>
                                @Html.TextBoxFor(model => model.ToDate, "{0:yyyy-MM-ddTHH:mm:ss}", new { @class = "form-control", @type = "datetime-local", @value = "model => model.FromDate" })
                                @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Logo</label>
                                @*<input type="file" name="LogoFile" class="form-control" />*@
                                @Html.TextBoxFor(model => model.LogoFile, new { @class = "form-control", @type = "file" })
                                <img src="@Model.Image" style="max-width:100%;height:80px;" />
                                @Html.ValidationMessageFor(model => model.LogoFile, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Trạng thái</label>
                                <select class="form-control" id="Status" name="Status">
                                    @if (Model.Status == 1)
                                    {
                                        <option value="1" selected>Hoạt động</option>
                                        <option value="0">Khóa</option>
                                    }
                                    else
                                    {
                                        <option value="1">Hoạt động</option>
                                        <option value="0" selected>Khóa</option>
                                    }
                                </select>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-5">
                                    <input type="submit" value="Sửa" class="btn btn-success" />
                                </div>
                            </div>
                        }
                        <div>
                            <a class="btn btn-danger" href="@Url.Action("Index", "Service", new { Area = "Admin" })">Quay lại</a>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

project tt/Areas/Admin/Views/Service/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var lstServices = (List<ProjectFinal.Models.Service>)ViewBag.ListService;
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Chiến dịch
        </h1>
        <ol class="breadcrumb">
            <li><a href="Admin/Home/Index"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            <li><a href="Admin/Product/Index">Chiến dịch</a></li>
            <li class="active">Danh sách chiến dịch</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"> <a class="btn btn-primary" href="@Url.Action("Create", "Service", new { Area = "Admin" })">Thêm mới</a></h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Ảnh</th>
                                    <th>Tên chiến dịch</th>
                                    <th>Số tiền</th>
                                    <th>Ngày bắt đầu</th>
                                    <th>Ngày kết thúc</th>
                                    <th>Trạng thái</th>
                                    <th>#</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    var stt = 0;
                                    foreach (var item in lstServices)
                                    {
                                        <tr>
                                            <td>@Html.Raw(stt = stt + 1)</td>
                                            <td><img src="@item.Image" style="width:60px;" /></td>
                                            <td>@item.Name</td>
                                            <td>@CommonUtil.RenderPrice(item.Money) đ</td>
                                            <td>@String.Format("{0:dd/MM/yyyy}", item.FromDate)</td>
                                            <td>@String.Format("{0:dd/MM/yyyy}", item.ToDate)</td>
                                             @if(item.Status == 1 && item.ToDate>DateTime.Now)
                                            {
                                                <td><span class="btn-success">Hoạt động</span></td>
                                            }
                                            else
                                            {
                                                <td><span class="btn-danger">Đang khóa</span></td>
                                            }
                                            <td>
                                                <a href="/Admin/Service/Edit/@item.Id" class="btn btn-danger">Sửa</a>
                                                <a class="btn btn-primary glyphicon glyphicon-trash" onclick="return confirm('Bạn có muốn xóa không?');" href="@Url.Action("Delete","Service")/@item.Id"></a>
                                            </td>
                                        </tr>
                                    }
                                }

                            </tbody>

                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>